# Generated by Django 6.0.3 on 2026-04-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_alter_dish_options_alter_mealrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
